export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';
export const SAVE_NOTE_SUCCESS = 'SAVE_NOTE_SUCCESS';
export const UPDATE_NOTES_SUCCESS = 'UPDATE_NOTES_SUCCESS';
